### ISSUE TITLE
App Center Build Crash

### ISSUE THREAD

**Issue by slatlas** [dmariogatto/Xamarin.Forms.BetterMaps#11]
I just wanted to first say thanks for putting this together. I was so impressed by your app and this package. So thank you!!

That being said, I'm having an issue, but only when my builds go through app center compiler. The app runs fine locally in the sim, and even running directly on my iphone via VS. The issue comes after I send it through app center and run it via test flight. The app crashes on startup, and the only way I've been able to get anything useful is through the console connected directly to my mac. The error code before it shuts down is a message about automapper not being registered in the IOC. We are using a framework called ASPnet Zero and the IOC container is Castle. I have tried manually registering automapper into the IOC with no luck. 

Is there something I am missing? Does it require registering components using the tinyIOC you used in the fuel app. 

Any help is greatly appreciated. 

-Ron

**Comment by dmariogatto** [comment]
The maps package shouldn't care what IoC container you're using.

My guess would be the linker is removing something it shouldn't when you're running in release. Have you tried debugging (either simulator/phone) with the same linker settings as you have for the release config?

**Comment by slatlas** [comment]
Thank you again! You were correct... it had nothing to do with the IOC. It ended up being autoMapper, which I was able to finally get a good error log by hooking my phone up directly to my mac and looking at the console logs. 

Here is what finally fixed it for anyone else.

https://medium.com/@deep_blue_day/fixing-automapper-runtime-errors-in-xamarin-forms-ios-13d5634c249e

<?xml version="1.0" encoding="UTF-8" ?>
<linker>
  <assembly fullname="mscorlib">
    <type fullname="System.Convert" preserve="All" />
  </assembly>
</linker>

You're map control is awesome, and I really appreciate you sharing this work. Cheers!
