### ISSUE TITLE
Offline Maps

### ISSUE THREAD

**Issue by slatlas** [dmariogatto/Xamarin.Forms.BetterMaps#14]
Just want to first thank you for putting this together. It works great! I have a request from our client to use offline maps in certain areas, is this something that can be accomplished with this package? 

Thanks again!!

**Comment by dmariogatto** [comment]
I don't think either of the native SDK's (Google Maps for Android and Apple Maps for iOS) have offline capability out-of-the-box - which is what this package used. I believe some of the 3rd party SDKs like MapBox allow for you to configure offline maps.
