### ISSUE TITLE
MapClicked vs PinClicked event

### ISSUE THREAD

**Issue by beukerz** [dmariogatto/Xamarin.Forms.BetterMaps#2]
Hi Daniel,
Me again, sorry for all the questions. I have implemented both mapClicked and pinClicked events. Both open a different popup page. The mapClicked event opens a popup to add a pin, the pinClicked event opens a popup to edit the pin. The problem I have is that if I click the pin the mapClicked event is triggered first and that popup is opened. The pinClicked event is triggered as well. Ideally I think the mapClicked event should not be triggered if a pin is selected. What do you think?

I tried to fix this myself in the OnMapClicked method in the renderer but the selected pin is not yet set when OnMapClicked kicks off and I can't find a way to get around this.

Thanks again,
Hugo

**Comment by dmariogatto** [comment]
@beukerz even on the latest version [1.3.0](https://www.nuget.org/packages/Xamarin.Forms.BetterMaps/1.3.0)?

**Comment by beukerz** [comment]
I did not see you released a new version, I should probably not answer from my phone during meetings...
It works perfectly! Thanks!
