### ISSUE TITLE
Crash - [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException

### ISSUE THREAD

**Issue by pasha-o** [dmariogatto/Xamarin.Forms.BetterMaps#9]
hi @dmariogatto 
When the map is created and during the rendering in Xaml, sometimes when you navigate away from the page, the following exception happens and the app crashes, perhaps there should be a way to dispose of the map object safely before rendering is incomplete.

crc6461ca18b415e724a6.OnMapCallback.onMapReady
OnMapCallback.java, line 30
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
crc6461ca18b415e724a6.OnMapCallback.n_onMapReady(Native Method)
crc6461ca18b415e724a6.OnMapCallback.onMapReady OnMapCallback.java:30
com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@17.0.1:1)
com.google.android.gms.maps.internal.zzaq.zza(com.google.android.gms:play-services-maps@@17.0.1:6)
com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@17.0.1:3)
android.os.Binder.transact Binder.java:1100
dy.aZ(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
com.google.maps.api.android.lib6.impl.bk.run(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):1)
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loopOnce Looper.java:226
android.os.Looper.loop Looper.java:313
android.app.ActivityThread.main ActivityThread.java:8663
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:567
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1135

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.BetterMaps.Android.OnMapCallback from native handle 0xffaefa24 (key_handle 0xefc698d). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.BetterMaps.Android.OnMapCallback::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
[mono-rt]   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, 03-23 20:29:09.906 F/mono-rt (21136):    --- End of inner exception stack trace ---
[mono-rt]   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00096] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:342 
[mono-rt]   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0010c] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:306 
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.193(intptr,intptr,intptr)
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.193(intptr,intptr,intptr)
[hw-BpHwBinder] onLastStrongRef automatically unlinking death recipients
[HostConnection] HostConnection::get() New Host Connection established 0xaac4c2c0, tid 21136
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
[sodrive.spotle] Background concurrent copying GC freed 3560(303KB) AllocSpace objects, 23(7460KB) LOS objects, 49% free, 10MB/21MB, paused 1.964ms total 133.306ms
[BpBinder] onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
[BpBinder] onLastStrongRef automatically unlinking death recipients: <uncached descriptor>

**Comment by dmariogatto** [comment]
@pasha-o Thanks for reporting!

I think this might be due to a missing method/constructor on the `OnMapCallback` class. I've released a new version that adds it in. Let me know if the issue persists.

**Comment by pasha-o** [comment]
@dmariogatto thanks for the prompt response - it seems your magic fixed the issue - always grateful for your work.

**Comment by pasha-o** [comment]
Hi @dmariogatto I was wondering if map control is already ported to Maui or is the work in progress? clicking on the Maui port currently errors out

**Comment by dmariogatto** [comment]
@pasha-o  Sorry, the repo was private - the link should work now.

The port is "complete", although I have done only very basic testing.
